//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListView
{
    using System;
    using System.Collections.Generic;
    
    public partial class comp
    {
        public int kod { get; set; }
        public string name { get; set; }
        public string model { get; set; }
        public Nullable<decimal> zena { get; set; }
        public byte[] images { get; set; }
    }
}
